import styles from '@/styles/Home.module.css'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import { useEffect } from 'react'
import { useAccount, useConnect, useDisconnect } from 'wagmi'
import { mainnet, optimism } from 'wagmi/chains'
import { CoinbaseWalletConnector } from 'wagmi/connectors/coinbaseWallet'
import { InjectedConnector } from 'wagmi/connectors/injected'
import { Button, Stack } from '@chakra-ui/react'
import { Container } from '@chakra-ui/react'
import WalletSDK from '@metamask/sdk'


const inter = Inter({ subsets: ['latin'] })

const metamaskConn = new InjectedConnector();
const coinbaseConn = new CoinbaseWalletConnector({
  chains: [mainnet, optimism],
  options: {
    appName: 'wagmish'
  },
})



export default function Home() {
  const { address, isConnected } = useAccount()
  const { connect } = useConnect({
    connector: coinbaseConn,
    onError(error) {
      console.log('Error connect CO', error)
    }
  })
  const { connect: connectMM } = useConnect({
    connector: metamaskConn,
    onError(error) {
      console.log('Error connect MM', error)
    }
  })
  const { disconnect } = useDisconnect({
    onError(error) {
      console.log('Error disconnect', error)
    },
  })
  useEffect(() => {
    new WalletSDK({
      useDeeplink: false,
      communicationLayerPreference: 'socket',
    })
    console.log("----init sdk");
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container>
          <Stack>
            <div>
            {isConnected ? <div>
              Connected to {address}
              <Button size='lg' onClick={() => disconnect()}>Disconnect</Button>
            </div> : <Stack><Button size='lg' onClick={() => { console.log("connCO"); connect() }}>Connect Wallet CO</Button>
            <Button size='lg' onClick={() => { console.log("connMMMM"); connectMM() }}>Connect MMM</Button></Stack>}
            </div>
            <Button onClick={() => alert("10000000")}>Alerto</Button>
          </Stack>
        </Container>
      </main>
    </>
  )
}
